CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255),
    avatar_url VARCHAR(2048),
    native_language VARCHAR(16),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    CONSTRAINT ck_users_email_not_blank CHECK (BTRIM(email) <> ''),
    CONSTRAINT ck_users_username_not_blank CHECK (BTRIM(username) <> '')
);

CREATE UNIQUE INDEX uk_users_email_lower ON users (LOWER(email));

CREATE TABLE languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_languages_code UNIQUE (code),
    CONSTRAINT ck_languages_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE language_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_language_levels_language FOREIGN KEY (language_id)
        REFERENCES languages (id) ON DELETE RESTRICT,
    CONSTRAINT uk_language_levels_language_code UNIQUE (language_id, code),
    CONSTRAINT ck_language_levels_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_level_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chapters_language_level FOREIGN KEY (language_level_id)
        REFERENCES language_levels (id) ON DELETE RESTRICT,
    CONSTRAINT uk_chapters_level_sort UNIQUE (language_level_id, sort_order),
    CONSTRAINT ck_chapters_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_chapters_level_enabled_sort
    ON chapters (language_level_id, enabled, sort_order);

CREATE TABLE grammar_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    grammar_rule TEXT NOT NULL,
    examples JSONB NOT NULL DEFAULT '[]'::JSONB,
    common_errors JSONB NOT NULL DEFAULT '[]'::JSONB,
    difficulty SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grammar_points_chapter FOREIGN KEY (chapter_id)
        REFERENCES chapters (id) ON DELETE RESTRICT,
    CONSTRAINT uk_grammar_points_chapter_code UNIQUE (chapter_id, code),
    CONSTRAINT ck_grammar_points_examples_array CHECK (jsonb_typeof(examples) = 'array'),
    CONSTRAINT ck_grammar_points_common_errors_array CHECK (jsonb_typeof(common_errors) = 'array'),
    CONSTRAINT ck_grammar_points_difficulty CHECK (difficulty BETWEEN 1 AND 5),
    CONSTRAINT ck_grammar_points_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_grammar_points_chapter_enabled_sort
    ON grammar_points (chapter_id, enabled, sort_order);

CREATE TABLE grammar_point_prerequisites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grammar_point_id BIGINT NOT NULL,
    prerequisite_grammar_point_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grammar_prerequisites_point FOREIGN KEY (grammar_point_id)
        REFERENCES grammar_points (id) ON DELETE CASCADE,
    CONSTRAINT fk_grammar_prerequisites_prerequisite FOREIGN KEY (prerequisite_grammar_point_id)
        REFERENCES grammar_points (id) ON DELETE CASCADE,
    CONSTRAINT uk_grammar_point_prerequisite UNIQUE (grammar_point_id, prerequisite_grammar_point_id),
    CONSTRAINT ck_grammar_prerequisite_not_self CHECK (grammar_point_id <> prerequisite_grammar_point_id)
);

CREATE INDEX idx_grammar_prerequisites_reverse
    ON grammar_point_prerequisites (prerequisite_grammar_point_id);

CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grammar_point_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    lesson_type VARCHAR(20) NOT NULL,
    xp_reward INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lessons_grammar_point FOREIGN KEY (grammar_point_id)
        REFERENCES grammar_points (id) ON DELETE RESTRICT,
    CONSTRAINT uk_lessons_grammar_point_sort UNIQUE (grammar_point_id, sort_order),
    CONSTRAINT ck_lessons_type CHECK (lesson_type IN ('LEARNING', 'PRACTICE', 'REVIEW')),
    CONSTRAINT ck_lessons_xp_reward CHECK (xp_reward >= 0),
    CONSTRAINT ck_lessons_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_lessons_grammar_enabled_sort
    ON lessons (grammar_point_id, enabled, sort_order);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL,
    grammar_point_id BIGINT NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    question_content TEXT NOT NULL,
    options JSONB,
    correct_answer JSONB NOT NULL,
    explanation TEXT NOT NULL,
    difficulty SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_questions_lesson FOREIGN KEY (lesson_id)
        REFERENCES lessons (id) ON DELETE RESTRICT,
    CONSTRAINT fk_questions_grammar_point FOREIGN KEY (grammar_point_id)
        REFERENCES grammar_points (id) ON DELETE RESTRICT,
    CONSTRAINT uk_questions_lesson_sort UNIQUE (lesson_id, sort_order),
    CONSTRAINT ck_questions_type CHECK (
        question_type IN (
            'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'FILL_BLANK',
            'SENTENCE_ORDER', 'TRUE_FALSE', 'CORRECTION'
        )
    ),
    CONSTRAINT ck_questions_options_json CHECK (
        options IS NULL OR jsonb_typeof(options) IN ('array', 'object')
    ),
    CONSTRAINT ck_questions_answer_json CHECK (
        jsonb_typeof(correct_answer) IN ('array', 'object', 'string', 'boolean', 'number')
    ),
    CONSTRAINT ck_questions_difficulty CHECK (difficulty BETWEEN 1 AND 5),
    CONSTRAINT ck_questions_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_questions_lesson_enabled_sort
    ON questions (lesson_id, enabled, sort_order);
CREATE INDEX idx_questions_grammar_point
    ON questions (grammar_point_id);

CREATE TABLE user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer JSONB NOT NULL,
    is_correct BOOLEAN NOT NULL,
    duration_ms INTEGER,
    answered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_answers_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_answers_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_answers_duration CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE INDEX idx_user_answers_user_answered_at
    ON user_answers (user_id, answered_at DESC);
CREATE INDEX idx_user_answers_question_answered_at
    ON user_answers (question_id, answered_at DESC);

CREATE TABLE user_lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    score SMALLINT NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    total_count INTEGER NOT NULL DEFAULT 0,
    xp_earned INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_lesson_progress_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_lesson_progress_lesson FOREIGN KEY (lesson_id)
        REFERENCES lessons (id) ON DELETE RESTRICT,
    CONSTRAINT uk_user_lesson_progress UNIQUE (user_id, lesson_id),
    CONSTRAINT ck_user_lesson_progress_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_user_lesson_progress_score CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT ck_user_lesson_progress_counts CHECK (
        correct_count >= 0 AND total_count >= 0 AND correct_count <= total_count
    ),
    CONSTRAINT ck_user_lesson_progress_xp CHECK (xp_earned >= 0),
    CONSTRAINT ck_user_lesson_progress_completed_at CHECK (
        (status = 'IN_PROGRESS' AND completed_at IS NULL)
        OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
    )
);

CREATE INDEX idx_user_lesson_progress_lesson
    ON user_lesson_progress (lesson_id);

CREATE TABLE user_learning_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    grammar_point_id BIGINT NOT NULL,
    mastery_score SMALLINT NOT NULL DEFAULT 0,
    total_questions INTEGER NOT NULL DEFAULT 0,
    correct_questions INTEGER NOT NULL DEFAULT 0,
    last_study_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_learning_progress_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_learning_progress_grammar_point FOREIGN KEY (grammar_point_id)
        REFERENCES grammar_points (id) ON DELETE RESTRICT,
    CONSTRAINT uk_user_learning_progress UNIQUE (user_id, grammar_point_id),
    CONSTRAINT ck_user_learning_mastery_score CHECK (mastery_score BETWEEN 0 AND 100),
    CONSTRAINT ck_user_learning_counts CHECK (
        total_questions >= 0 AND correct_questions >= 0 AND correct_questions <= total_questions
    )
);

CREATE INDEX idx_user_learning_progress_grammar
    ON user_learning_progress (grammar_point_id);

CREATE TABLE wrong_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    wrong_count INTEGER NOT NULL DEFAULT 1,
    last_wrong_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_review_at TIMESTAMPTZ,
    mastered BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wrong_questions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_wrong_questions_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE RESTRICT,
    CONSTRAINT uk_wrong_questions_user_question UNIQUE (user_id, question_id),
    CONSTRAINT ck_wrong_questions_count CHECK (wrong_count >= 1)
);

CREATE INDEX idx_wrong_questions_review_queue
    ON wrong_questions (user_id, mastered, next_review_at);
CREATE INDEX idx_wrong_questions_question
    ON wrong_questions (question_id);

CREATE TABLE user_streaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    current_streak INTEGER NOT NULL DEFAULT 0,
    max_streak INTEGER NOT NULL DEFAULT 0,
    last_learning_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_streaks_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_streaks_user UNIQUE (user_id),
    CONSTRAINT ck_user_streaks_values CHECK (
        current_streak >= 0 AND max_streak >= 0 AND current_streak <= max_streak
    )
);

