CREATE TABLE lesson_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    total_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    score SMALLINT NOT NULL DEFAULT 0,
    xp_earned INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lesson_attempts_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_attempts_lesson FOREIGN KEY (lesson_id)
        REFERENCES lessons (id) ON DELETE RESTRICT,
    CONSTRAINT ck_lesson_attempts_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_lesson_attempts_score CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT ck_lesson_attempts_counts CHECK (
        correct_count >= 0 AND total_count >= 0 AND correct_count <= total_count
    ),
    CONSTRAINT ck_lesson_attempts_xp CHECK (xp_earned >= 0),
    CONSTRAINT ck_lesson_attempts_completed_at CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status = 'IN_PROGRESS' AND completed_at IS NULL)
    )
);

-- At most one in-progress attempt per user and lesson, so find-or-create is safe
-- without blocking on a full table lock.
CREATE UNIQUE INDEX uk_lesson_attempts_active
    ON lesson_attempts (user_id, lesson_id)
    WHERE status = 'IN_PROGRESS';

-- Dashboard aggregates: today's completions and XP, and lifetime XP.
CREATE INDEX idx_lesson_attempts_user_completed
    ON lesson_attempts (user_id, completed_at)
    WHERE completed_at IS NOT NULL;

ALTER TABLE user_answers
    ADD COLUMN lesson_attempt_id BIGINT;

ALTER TABLE user_answers
    ADD CONSTRAINT fk_user_answers_lesson_attempt
        FOREIGN KEY (lesson_attempt_id) REFERENCES lesson_attempts (id) ON DELETE SET NULL;

CREATE INDEX idx_user_answers_lesson_attempt
    ON user_answers (lesson_attempt_id);
